<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup Label="Marten">
    <PackageVersion Include="Marten" Version="9.19.0" />
  </ItemGroup>

  <ItemGroup Label="DI">
    <PackageVersion
      Include="Microsoft.Extensions.DependencyInjection.Abstractions"
      Version="10.0.10"
    />
  </ItemGroup>

  <ItemGroup Label="DataProtection">
    <PackageVersion Include="Microsoft.AspNetCore.DataProtection.Abstractions" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup Label="Testing">
    <PackageVersion Include="AndreGoepel.Marten.Testing" Version="1.0.0" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>
</Project>
