name: CI
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    uses: andregoepel/workflows/.github/workflows/ci-library.yml@main
    with:
      pack-projects: |
        src/AndreGoepel.Marten.Configuration/AndreGoepel.Marten.Configuration.csproj
    secrets:
      NUGET_USER: ${{ secrets.NUGET_USER }}
    permissions:
      id-token: write # NuGet OIDC trusted publishing
      contents: read
